## **1. Importing NumPy**
By convention, NumPy is always imported with the alias **np**.

In [2]:
import numpy as np

## **2. The NumPy ndarray**
The core object is the ndarray (n-dimensional array). It's a grid of values, all of the same type.
- From a Python List: The most common way to create an array.

In [4]:
list2d = [[1, 2, 3], [4, 5, 6]]
arr2d = np.array(list2d)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

- Attributes of an Array:
    - **ndim:** The number of dimensions (or axes).
    - **shape:** A tuple indicating the size of the array in each dimension.
    - **size:** The total number of elements in the array.
    - **dtype:** The data type of the elements in the array.

In [2]:
# 1-dimensional array (vector)
list1 = [1, 2, 3, 4, 5]
arr1d = np.array(list1)

print("1D Array:")
print(arr1d)
print(f"Dimensions (ndim): {arr1d.ndim}")
print(f"Shape: {arr1d.shape}") # Note the comma, indicating it's a tuple
print(f"Size: {arr1d.size}")
print(f"Data type (dtype): {arr1d.dtype}")

# 2-dimensional array (matrix)
list2 = [[1, 2, 3], [4, 5, 6]]
arr2d = np.array(list2)

print("\n2D Array:")
print(arr2d)
print(f"Dimensions (ndim): {arr2d.ndim}")
print(f"Shape: {arr2d.shape}") # (2 rows, 3 columns)
print(f"Size: {arr2d.size}")
print(f"Data type (dtype): {arr2d.dtype}")

# Specifying the data type on creation
arr_float = np.array([1, 2, 3], dtype=np.float64)
print(f"\nFloat array dtype: {arr_float.dtype}")

1D Array:
[1 2 3 4 5]
Dimensions (ndim): 1
Shape: (5,)
Size: 5
Data type (dtype): int64

2D Array:
[[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2
Shape: (2, 3)
Size: 6
Data type (dtype): int64

Float array dtype: float64


## **3. Built-in Array Creation Functions**
NumPy provides functions to create arrays from scratch, which is very common.
- **np.zeros(shape):** Creates an array of the given shape, filled with zeros.
- **np.ones(shape):** Creates an array filled with ones.
- **np.full(shape, fill_value):** Creates an array of the given shape, filled with a specific value.
- **np.arange(start, stop, step):** Like Python's range(), but returns a NumPy array.
- **np.linspace(start, stop, num):** Creates an array with a specified number (num) of evenly spaced values between start and stop (inclusive).
- **np.random.rand(d0, d1, ...):** Creates an array of the given shape with random values in [0, 1).
- **np.random.randn(d0, d1, ...):** Creates an array of the given shape with random values from a standard normal distribution (mean 0, variance 1).
- **np.random.randint(low, high, size):** Creates an array of the given size with random integers between low (inclusive) and high (exclusive).
- **np.eye(N):** Creates an N x N identity matrix (ones on the diagonal, zeros elsewhere).

In [5]:
# Create a 3x4 array of zeros
zeros_arr = np.zeros((3, 4))
print(f"\nZeros array:\n{zeros_arr}")

# Create a 2x3x2 array of ones
ones_arr = np.ones((2, 3, 2))
print(f"\nOnes array:\n{ones_arr}")

# Create an array from 0 to 19
range_arr = np.arange(20)
print(f"\nArange array:\n{range_arr}")

# Create 5 evenly spaced numbers between 0 and 10
linspace_arr = np.linspace(0, 10, 5)
print(f"\nLinspace array:\n{linspace_arr}")

# Create a 2x3 array of random numbers (uniform distribution)
rand_arr = np.random.rand(2, 3)
print(f"\nRandom uniform array:\n{rand_arr}")

# Create a 3x3 array of random integers between 1 and 100
randint_arr = np.random.randint(1, 101, size=(3, 3))
print(f"\nRandom integer array:\n{randint_arr}")


Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]

Arange array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Linspace array:
[ 0.   2.5  5.   7.5 10. ]

Random uniform array:
[[0.65528952 0.61402548 0.64254285]
 [0.93754225 0.87300696 0.94025591]]

Random integer array:
[[47 98 87]
 [12 58 72]
 [67 61 49]]


## **4. The "Amaze" Factor: Vectorization and Performance**
This is the most important concept. Let's see why NumPy is fast. We'll time the same operation (squaring every element in a sequence) using a standard Python for loop vs. a vectorized NumPy operation.

In [6]:
# Create a large sequence of numbers
# Using a Python list
python_list = list(range(1_000_000))

# Using a NumPy array
numpy_array = np.arange(1_000_000)

# Time the Python for loop
# %timeit is a Jupyter magic command that runs the code multiple times
# to get an accurate measurement of its execution time.
print("Timing the Python for loop:")
%timeit squared_list = [x**2 for x in python_list]

# Time the vectorized NumPy operation
print("\nTiming the vectorized NumPy operation:")
%timeit squared_array = numpy_array ** 2

Timing the Python for loop:
105 ms ± 2.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Timing the vectorized NumPy operation:
4.02 ms ± 79.3 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## **Exercises**

**1. Array from List:**
- Create a Python list of numbers [10, 20, 30, 40, 50].
- Convert this list into a NumPy array.
- Create a Python nested list [[1, 2], [3, 4], [5, 6]].
- Convert this nested list into a 2D NumPy array.
- Print both arrays and their shape and ndim attributes.

In [16]:
print("********")
list1 = [10, 20, 30, 40, 50]
arr1d = np.array(list1)
print(f" NumPy Array:\n {arr1d}")
print(f"Shape: {arr1d.shape}")
print(f"Dimention: {arr1d.ndim}")
print("\n********")

list2 = [[1, 2], [3, 4], [5, 6]]
arr2d = np.array(list2)
print(f" NumPy Array:\n {arr2d}")
print(f"Shape: {arr2d.shape}")
print(f"Dimention: {arr2d.ndim}")

********
 NumPy Array:
 [10 20 30 40 50]
Shape: (5,)
Dimention: 1

********
 NumPy Array:
 [[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)
Dimention: 2


**2. Specialized Arrays:**
- Create a 3x3 NumPy array filled with the value 8, using np.full().
- Create a NumPy array of all the even numbers from 20 to 50 (inclusive) using np.arange().
- Create a 4x4 identity matrix using np.eye().
- Print all three arrays.

In [23]:
arr = np.full([3,3], 8)
print(f"3x3 NumPy array filled with the value 8:\n{arr}")

arr2 = np.arange(20,51,2)
print(f"\nA NumPy array of all the even numbers from 20 to 50:\n{arr2}")

arr3 = np.eye(4)
print(f"\nA 4x4 identity matrix:\n{arr3}")

3x3 NumPy array filled with the value 8:
[[8 8 8]
 [8 8 8]
 [8 8 8]]

A NumPy array of all the even numbers from 20 to 50:
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

A 4x4 identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**3. Random Number Generation and Basic Stats:**
- Create a 5x5 NumPy array of random integers between 10 and 20 (inclusive of 10, exclusive of 21).
Print the array.
- From this array, find and print the maximum value, minimum value, and the overall sum of all elements (Hint: look for array methods like .max(), .min(), and .sum()).

In [30]:
arr4 = np.random.randint(10,20, size = (5,5))
print(f"\nA 5x5 NumPy array of random integers between 10 and 20:\n{arr4}")
print(f"Maximum Value: {arr4.max()}")
print(f"Minimum Value: {arr4.min()}")
print(f"Sum: {arr4.sum()}")


A 5x5 NumPy array of random integers between 10 and 20:
[[13 10 16 11 16]
 [18 16 13 10 11]
 [13 19 10 16 15]
 [10 12 13 15 16]
 [18 17 16 16 16]]
Maximum Value: 19
Minimum Value: 10
Sum: 356
