## **1. Basic Indexing and Slicing**
This works very similarly to Python lists, but extends to multiple dimensions.

In [2]:
import numpy as np

# 1D Array Slicing (same as lists)
arr1d = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(f"Original 1D array: {arr1d}")
print(f"Element at index 3: {arr1d[3]}")
print(f"Elements from index 2 to 5 (exclusive): {arr1d[2:5]}")

# 2D Array Indexing and Slicing
# Think of it as [row, column]
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nOriginal 2D array:\n{arr2d}")

# Get a single element (row 1, column 2)
element = arr2d[1, 2] # The element is 6
print(f"\nElement at [1, 2]: {element}")

# Alternative syntax (less common)
element_alt = arr2d[1][2]
print(f"Element at [1][2]: {element_alt}")

# Slicing 2D arrays
# Get the first two rows
slice1 = arr2d[:2, :] # Rows 0-1, all columns
print(f"\nFirst two rows:\n{slice1}")

# Get the last two columns
slice2 = arr2d[:, 1:] # All rows, columns 1-2
print(f"\nLast two columns:\n{slice2}")

# Get a sub-matrix (a 2x2 from the top right)
sub_matrix = arr2d[:2, 1:] # Rows 0-1, columns 1-2
print(f"\nTop right 2x2 sub-matrix:\n{sub_matrix}")

Original 1D array: [0 1 2 3 4 5 6 7 8 9]
Element at index 3: 3
Elements from index 2 to 5 (exclusive): [2 3 4]

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at [1, 2]: 6
Element at [1][2]: 6

First two rows:
[[1 2 3]
 [4 5 6]]

Last two columns:
[[2 3]
 [5 6]
 [8 9]]

Top right 2x2 sub-matrix:
[[2 3]
 [5 6]]


**Important Note on Slices: Views vs. Copies**
- Unlike Python lists, NumPy array slices are views into the original array. This means if you modify a slice, you are also modifying the original array. This is done for performance reasons to avoid copying large amounts of data.
- To create an explicit copy, use the **.copy()** method.

In [2]:
# Create an array
original_arr = np.arange(10)
print(f"\nOriginal array: {original_arr}")

# Create a slice (a view)
slice_arr = original_arr[5:8]
print(f"Slice: {slice_arr}")

# Modify an element in the slice
slice_arr[1] = 999
print(f"Slice after modification: {slice_arr}")

# The original array is also changed!
print(f"Original array after modifying slice: {original_arr}")

# To avoid this, use .copy()
original_arr2 = np.arange(10)
slice_copy = original_arr2[5:8].copy()
slice_copy[1] = 777
print(f"\nOriginal array 2: {original_arr2}") # Unchanged
print(f"Copied slice after modification: {slice_copy}")


Original array: [0 1 2 3 4 5 6 7 8 9]
Slice: [5 6 7]
Slice after modification: [  5 999   7]
Original array after modifying slice: [  0   1   2   3   4   5 999   7   8   9]

Original array 2: [0 1 2 3 4 5 6 7 8 9]
Copied slice after modification: [  5 777   7]


## **2. Boolean Indexing (Masking)**
This is an extremely powerful feature for data analysis. You can select elements from an array based on a condition.
- Apply a condition to an array (e.g., arr > 5). This produces a boolean array of True/False values.
- Use this boolean array (the "mask") inside square brackets [] to select only the elements from the original array where the mask is True.

In [3]:
data = np.random.randint(1, 51, size=(4, 5))
print(f"Original data:\n{data}")

# Create a boolean mask for values greater than 25
mask = data > 25
print(f"\nBoolean mask (data > 25):\n{mask}")

# Use the mask to select the elements
selected_data = data[mask]
print(f"\nElements greater than 25: {selected_data}")

# You can do this in one line
print(f"\nElements less than 10 (one line): {data[data < 10]}")

# You can also use boolean indexing to modify values
# Set all even numbers to 0
data[data % 2 == 0] = 0
print(f"\nData after setting even numbers to 0:\n{data}")

Original data:
[[10  2 37 17 23]
 [10 35 14 50 45]
 [23 17 13 11 21]
 [22 27 44 35 34]]

Boolean mask (data > 25):
[[False False  True False False]
 [False  True False  True  True]
 [False False False False False]
 [False  True  True  True  True]]

Elements greater than 25: [37 35 50 45 27 44 35 34]

Elements less than 10 (one line): [2]

Data after setting even numbers to 0:
[[ 0  0 37 17 23]
 [ 0 35  0  0 45]
 [23 17 13 11 21]
 [ 0 27  0 35  0]]


## **3. Fancy Indexing**
This allows you to select elements using an array of indices.

In [4]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Select elements at specific indices
indices = [1, 3, 6]
print(f"\nSelected elements using fancy indexing: {arr[indices]}")

# For 2D arrays, you can pass a tuple of index arrays: one for rows, one for columns
arr2d = np.arange(12).reshape((4, 3))
print(f"\nOriginal 2D array:\n{arr2d}")

# Select elements at (row 0, col 1), (row 2, col 2), and (row 3, col 0)
row_indices = [0, 2, 3]
col_indices = [1, 2, 0]
selected = arr2d[row_indices, col_indices]
print(f"\nSelected specific elements from 2D array: {selected}")


Selected elements using fancy indexing: [20 40 70]

Original 2D array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Selected specific elements from 2D array: [1 8 9]


## **4. Universal Functions (ufuncs) and Mathematical Operations**
This is vectorization in action. NumPy operations are applied element-wise to entire arrays without needing Python loops.

In [5]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

# Element-wise operations
print(f"\nx + y = {x + y}")
print(f"x * y = {x * y}")
print(f"x / 2 = {x / 2}")
print(f"x ** 2 = {x ** 2}")

# Universal functions
print(f"\nSquare root of x: {np.sqrt(x)}")
print(f"Exponential of x: {np.exp(x)}")
print(f"Sine of x: {np.sin(x)}")
print(f"Maximum of x and y element-wise: {np.maximum(x, y)}")


x + y = [ 6  8 10 12]
x * y = [ 5 12 21 32]
x / 2 = [0.5 1.  1.5 2. ]
x ** 2 = [ 1  4  9 16]

Square root of x: [1.         1.41421356 1.73205081 2.        ]
Exponential of x: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Sine of x: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Maximum of x and y element-wise: [5 6 7 8]


## **Exercises**

**1. Slicing Practice:**
- Create a 2D NumPy array with a shape of (5, 5) containing integers from 1 to 25. (Hint: np.arange(1, 26).reshape(5, 5)).
- From this array, extract a 3x3 sub-array from the center of the original array.
- Extract the entire last column of the array.
- Extract every other element from the 3rd row.
- Print the original array and all three extracted parts.

In [21]:
arr2d = np.arange(1,26).reshape(5,5)
sub_arr = arr2d[1:4, 1:4]
last_column = arr2d[:,4:]
third_row = arr2d[2,::2]
print(f"Original Array:\n{arr2d}")
print(f"\nA 3x3 sub-array from the center of the original array:\n{sub_arr}")
print(f"\nLast column of the array:\n{last_column}")
print(f"\nEvery other element from the 3rd row:\n{third_row}")

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

A 3x3 sub-array from the center of the original array:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Last column of the array:
[[ 5]
 [10]
 [15]
 [20]
 [25]]

Every other element from the 3rd row:
[11 13 15]


**2. Data Filtering with Boolean Masking:**
- Create a 1D NumPy array with 10 random integers between -50 and 50.
- Create a boolean mask to find all the positive numbers in the array.
- Use the mask to select and print only the positive numbers.
- In a single line, replace all negative numbers in the original array with 0 and print the modified array.

In [14]:
arr1d = np.random.randint(-50,51,10)
print(f"Original Array: {arr1d}")
mask = arr1d > 0
positive_numbers = arr1d[mask]
print(f"All the positive numbers in the array is: {positive_numbers}")
arr1d[arr1d <0] = 0
print(f"Modifid Array: {arr1d}")

Original Array: [-29   6 -26 -50 -23 -10   1  -4  36 -25]
All the positive numbers in the array is: [ 6  1 36]
Modifid Array: [ 0  6  0  0  0  0  1  0 36  0]


**3. Views vs. Copies:**
- Create a 1D NumPy array of numbers from 0 to 9.
- Create a slice of this array containing the elements from index 5 onwards. Name this slice my_view.
- Create a copy of this same slice. Name this copy my_copy.
- Modify the first element of my_view to be 99.
- Modify the second element of my_copy to be 777.
- Print the original array, my_view, and my_copy to observe the differences. Explain in a Markdown cell why the original array changed in one case but not the other.

In [23]:
arr1d = np.arange(0,10)
print(f"Before modification Original Array: {arr1d}")
my_view = arr1d[5:]
my_copy = arr1d[5:].copy()
my_view[0] = 99
my_copy[1] = 777
print(f"After modification Original Array: {arr1d}")
print(f"my_view: {my_view}")
print(f"my_copy: {my_copy}")

Before modification Original Array: [0 1 2 3 4 5 6 7 8 9]
After modification Original Array: [ 0  1  2  3  4 99  6  7  8  9]
my_view: [99  6  7  8  9]
my_copy: [  5 777   7   8   9]


- **Explaination**
The original array arr1d was modified when we changed my_view, but not when we changed my_copy. This happens because of how NumPy handles memory for performance:
    - 